dubai_mall = [
    {"Brand": "Apple Store", "Category": "Electronics", "Floor": "Ground Floor"},
    {"Brand": "Bang & Olufsen", "Category": "Electronics", "Floor": "First Floor"},
    {"Brand": "Bose", "Category": "Electronics", "Floor": "Second Floor"},
    {"Brand": "Canon", "Category": "Electronics", "Floor": "Second Floor"},
    {"Brand": "Dirham 4U Electronics", "Category": "Electronics", "Floor": "Second Floor"},
    {"Brand": "Dyson", "Category": "Electronics", "Floor": "Second Floor"},
    {"Brand": "E City", "Category": "Electronics", "Floor": "Second Floor"},
    {"Brand": "E Max", "Category": "Electronics", "Floor": "Second Floor"},
    {"Brand": "Geekay Games", "Category": "Electronics", "Floor": "Second Floor"},
    {"Brand": "Grand Stores Digital", "Category": "Electronics", "Floor": "Lower Ground Floor"},
    {"Brand": "Grand Stores Digital", "Category": "Electronics", "Floor": "Second Floor"},
    {"Brand": "HI Phone", "Category": "Electronics", "Floor": "Second Floor"},
    {"Brand": "HONOR", "Category": "Electronics", "Floor": "Second Floor"},
    {"Brand": "Harman House", "Category": "Electronics", "Floor": "Second Floor"},
    {"Brand": "Huawei", "Category": "Electronics", "Floor": "Second Floor"},
    {"Brand": "IQOS", "Category": "Electronics", "Floor": "First Floor"},
    {"Brand": "Jumbo Electronics", "Category": "Electronics", "Floor": "Second Floor"},
    {"Brand": "Leica", "Category": "Electronics", "Floor": "Ground Floor"},
    {"Brand": "Mumuso", "Category": "Electronics", "Floor": "Second Floor"},
    {"Brand": "Mumuso", "Category": "Electronics", "Floor": "Lower Ground Floor"},
    {"Brand": "My Vapery", "Category": "Electronics", "Floor": "Lower Ground Floor"},
    {"Brand": "O Vape", "Category": "Electronics", "Floor": "Second Floor"},
    {"Brand": "PORSCHE DESIGN", "Category": "Electronics", "Floor": "First Floor"},
    {"Brand": "Phonebook", "Category": "Electronics", "Floor": "Second Floor"},
    {"Brand": "Ring", "Category": "Electronics", "Floor": "Second Floor"},
    {"Brand": "Sadek Music", "Category": "Electronics", "Floor": "Second Floor"},
    {"Brand": "Samsung", "Category": "Electronics", "Floor": "Second Floor"},
    {"Brand": "Sharaf DG", "Category": "Electronics", "Floor": "Second Floor"},
    {"Brand": "Sony", "Category": "Electronics", "Floor": "Second Floor"},
    {"Brand": "Virgin Megastore", "Category": "Electronics", "Floor": "Second Floor"},
    {"Brand": "Virgin Mobile", "Category": "Electronics", "Floor": "Lower Ground Floor"},
    {"Brand": "Yamaha", "Category": "Electronics", "Floor": "Second Floor"},
    {"Brand": "ZGAMES", "Category": "Electronics", "Floor": "Second Floor"},

    # Fashion & Apparel
    {"Brand": "100% Capri", "Category": "Fashion & Apparel", "Floor": "First Floor"},
    {"Brand": "800 Leather", "Category": "Fashion & Apparel", "Floor": "Second Floor"},
    {"Brand": "A BATHING APE", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "AAPE", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "ADIDAS", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "AIZONE", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "ALL SAINTS", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "AMERICAN RAG CIE", "Category": "Fashion & Apparel", "Floor": "Second Floor"},
    {"Brand": "ANTLER", "Category": "Fashion & Apparel", "Floor": "Lower Ground Floor"},
    {"Brand": "Abercrombie & Fitch", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "Adidas Originals", "Category": "Fashion & Apparel", "Floor": "Second Floor"},
    {"Brand": "Alexander McQueen", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "American Vintage", "Category": "Fashion & Apparel", "Floor": "First Floor"},
    {"Brand": "Armani Exchange", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "B1", "Category": "Fashion & Apparel", "Floor": "First Floor"},
    {"Brand": "B180", "Category": "Fashion & Apparel", "Floor": "Second Floor"},
    {"Brand": "BOSS", "Category": "Fashion & Apparel", "Floor": "First Floor"},
    {"Brand": "BRIONI", "Category": "Fashion & Apparel", "Floor": "First Floor"},
    {"Brand": "Balenciaga", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "Bally", "Category": "Fashion & Apparel", "Floor": "First Floor"},
    {"Brand": "Balmain", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "Balmain", "Category": "Fashion & Apparel", "Floor": "Second Floor"},
    {"Brand": "Beverly Hills Polo Club", "Category": "Fashion & Apparel", "Floor": "First Floor"},
    {"Brand": "Bloomingdale's", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "Boggi Milano", "Category": "Fashion & Apparel", "Floor": "First Floor"},
    {"Brand": "Boris Becker", "Category": "Fashion & Apparel", "Floor": "Second Floor"},
    {"Brand": "Bottega Veneta", "Category": "Fashion & Apparel", "Floor": "Lobby"},
    {"Brand": "Brooks Brothers", "Category": "Fashion & Apparel", "Floor": "First Floor"},
    {"Brand": "Brunello Cucinelli", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "Burberry", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "Bvlgari", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "CHANEL", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "CHARLES TYRWHITT", "Category": "Fashion & Apparel", "Floor": "First Floor"},
    {"Brand": "CRYPT", "Category": "Fashion & Apparel", "Floor": "Second Floor"},
    {"Brand": "Caliente", "Category": "Fashion & Apparel", "Floor": "First Floor"},
    {"Brand": "Calvin Klein", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "Canali", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "Carolina Herrera", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "Caterpillar", "Category": "Fashion & Apparel", "Floor": "Second Floor"},
    {"Brand": "Centrepoint", "Category": "Fashion & Apparel", "Floor": "First Floor"},
    {"Brand": "Cesare Paciotti", "Category": "Fashion & Apparel", "Floor": "First Floor"},
    {"Brand": "Chic", "Category": "Fashion & Apparel", "Floor": "First Floor"},
    {"Brand": "Christian Audigier", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "Christian Louboutin", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "Clarks", "Category": "Fashion & Apparel", "Floor": "Second Floor"},
    {"Brand": "Closet Case", "Category": "Fashion & Apparel", "Floor": "Second Floor"},
    {"Brand": "Coach", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "Cole Haan", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "Converse", "Category": "Fashion & Apparel", "Floor": "Second Floor"},
    {"Brand": "Crocs", "Category": "Fashion & Apparel", "Floor": "Second Floor"},
    {"Brand": "D's Damat", "Category": "Fashion & Apparel", "Floor": "First Floor"},
    {"Brand": "Da Milano", "Category": "Fashion & Apparel", "Floor": "First Floor"},
    {"Brand": "Damas", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "Diesel", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "Dior", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "Dolce&Gabbana", "Category": "Fashion & Apparel", "Floor": "Lobby"},
    {"Brand": "Doppelganger", "Category": "Fashion & Apparel", "Floor": "First Floor"},
    {"Brand": "Ecco", "Category": "Fashion & Apparel", "Floor": "First Floor"},
    {"Brand": "Etro", "Category": "Fashion & Apparel", "Floor": "First Floor"},
    {"Brand": "FAURE LE PAGE", "Category": "Fashion & Apparel", "Floor": "First Floor"},
    {"Brand": "FEDELI", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "Fendi", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "Ferragamo", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "GIANFRANCO FERRE", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "GIUSEPPE ZANOTTI", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "GLOBAL FEET", "Category": "Fashion & Apparel", "Floor": "Second Floor"},
    {"Brand": "GOLDEN GOOSE", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "Giorgio Armani", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "Givenchy", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "Go Sport", "Category": "Fashion & Apparel", "Floor": "Second Floor"},
    {"Brand": "Gucci", "Category": "Fashion & Apparel", "Floor": "Blvd Level"},
    {"Brand": "Guess", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "H&M", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "HUGO", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "Hamac", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "Hanro", "Category": "Fashion & Apparel", "Floor": "Second Floor"},
    {"Brand": "Kiton", "Category": "Fashion & Apparel", "Floor": "First Floor"},
    {"Brand": "LC WAIKIKI", "Category": "Fashion & Apparel", "Floor": "First Floor"},
    {"Brand": "LIVERPOOL FC", "Category": "Fashion & Apparel", "Floor": "Lower Ground Floor"},
    {"Brand": "LOUIS VUITTON", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "Lefties", "Category": "Fashion & Apparel", "Floor": "First Floor"},
    {"Brand": "Level Shoes", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "Levi's", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "Loewe", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "Loro Piana", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "Louis Feraud", "Category": "Fashion & Apparel", "Floor": "First Floor"},
    {"Brand": "Louis Feraud", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "Lululemon Athletica", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "MANEBI", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "MANGO Man", "Category": "Fashion & Apparel", "Floor": "First Floor"},
    {"Brand": "MARKS & SPENCER", "Category": "Fashion & Apparel", "Floor": "First Floor"},
    {"Brand": "MAYBACH", "Category": "Fashion & Apparel", "Floor": "Second Floor"},
    {"Brand": "MCM", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "Maison Balmain", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "Maison Margiela", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "Manish Malhotra", "Category": "Fashion & Apparel", "Floor": "Second Floor"},
    {"Brand": "Mansour Jewellers", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "Massimo Dutti", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "Matalan", "Category": "Fashion & Apparel", "Floor": "Second Floor"},
    {"Brand": "Max", "Category": "Fashion & Apparel", "Floor": "Second Floor"},
    {"Brand": "Moncler", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "Moynat", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "Mumuso", "Category": "Fashion & Apparel", "Floor": "Second Floor"},
    {"Brand": "Nautica", "Category": "Fashion & Apparel", "Floor": "Second Floor"},
    {"Brand": "Nike", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "Nike Town", "Category": "Fashion & Apparel", "Floor": "Second Floor"},
    {"Brand": "Nous", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "OFF-AIZONE", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "ORLEBAR BROWN", "Category": "Fashion & Apparel", "Floor": "First Floor"},
    {"Brand": "Oakley", "Category": "Fashion & Apparel", "Floor": "Second Floor"},
    {"Brand": "PAL ZILERI", "Category": "Fashion & Apparel", "Floor": "First Floor"},
    {"Brand": "PAUL & SHARK", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "PORSCHE DESIGN", "Category": "Fashion & Apparel", "Floor": "First Floor"},
    {"Brand": "PRADA", "Category": "Fashion & Apparel", "Floor": "Lobby"},
    {"Brand": "Party Zone", "Category": "Fashion & Apparel", "Floor": "Second Floor"},
    {"Brand": "Patrizia Pepe", "Category": "Fashion & Apparel", "Floor": "First Floor"},
    {"Brand": "Philipp Plein", "Category": "Fashion & Apparel", "Floor": "First Floor"},
    {"Brand": "Pierre Cardin", "Category": "Fashion & Apparel", "Floor": "Second Floor"},
    {"Brand": "Pierre Cardin", "Category": "Fashion & Apparel", "Floor": "Lower Ground Floor"},
    {"Brand": "Pierre Cardin", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "Pitstop", "Category": "Fashion & Apparel", "Floor": "Second Floor"},
    {"Brand": "Pleats Please", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "Pull&Bear", "Category": "Fashion & Apparel", "Floor": "First Floor"},
    {"Brand": "Puma", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "REISS", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "RESERVED", "Category": "Fashion & Apparel", "Floor": "First Floor"},
    {"Brand": "Ralph Lauren", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "Replay", "Category": "Fashion & Apparel", "Floor": "Second Floor"},
    {"Brand": "Rick Owens", "Category": "Fashion & Apparel", "Floor": "First Floor"},
    {"Brand": "Royal Fashion", "Category": "Fashion & Apparel", "Floor": "Second Floor"},
    {"Brand": "SAINT LAURENT", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "SALEM ALTA MODA", "Category": "Fashion & Apparel", "Floor": "Second Floor"},
    {"Brand": "SALSA JEANS", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "Sacoor Brothers", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "Scotch & Soda", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "St. John", "Category": "Fashion & Apparel", "Floor": "First Floor"},
    {"Brand": "Stefano Ricci", "Category": "Fashion & Apparel", "Floor": "First Floor"},
    {"Brand": "Stitch In Time Tailoring", "Category": "Fashion & Apparel", "Floor": "Lower Ground Floor"},
    {"Brand": "Superdry", "Category": "Fashion & Apparel", "Floor": "Second Floor"},
    {"Brand": "TOMS", "Category": "Fashion & Apparel", "Floor": "First Floor"},
    {"Brand": "The Bag House", "Category": "Fashion & Apparel", "Floor": "Lower Ground Floor"},
    {"Brand": "The North Face", "Category": "Fashion & Apparel", "Floor": "Second Floor"},
    {"Brand": "Thom Browne", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "Tod's", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "Tommy Hilfiger", "Category": "Fashion & Apparel", "Floor": "First Floor"},
    {"Brand": "Tommy Hilfiger Footwear & Accessories", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "U.S. Polo Assn", "Category": "Fashion & Apparel", "Floor": "Second Floor"},
    {"Brand": "Urban Outfitters", "Category": "Fashion & Apparel", "Floor": "First Floor"},
    {"Brand": "Varsity Headwear", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "Versace", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "Vilebrequin", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "ZIMMERLI OF SWITZERLAND", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "Zara", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "Zegna", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},
    {"Brand": "Zilli", "Category": "Fashion & Apparel", "Floor": "Ground Floor"},

    # Home & Lifestyle
    {"Brand": "ANTHROPOLOGIE", "Category": "Home & Lifestyle", "Floor": "Ground Floor"},
    {"Brand": "ARMANI/CASA", "Category": "Home & Lifestyle", "Floor": "Lower Ground Floor"},
    {"Brand": "AURA LIVING", "Category": "Home & Lifestyle", "Floor": "Lower Ground Floor"},
    {"Brand": "BENTLEY HOME", "Category": "Home & Lifestyle", "Floor": "Lower Ground Floor"},
    {"Brand": "BUGATTI HOME", "Category": "Home & Lifestyle", "Floor": "Lower Ground Floor"},
    {"Brand": "Baccarat", "Category": "Home & Lifestyle", "Floor": "First Floor"},
    {"Brand": "Bernardaud", "Category": "Home & Lifestyle", "Floor": "First Floor"},
    {"Brand": "Bloomingdale's Home", "Category": "Home & Lifestyle", "Floor": "Lower Ground Floor"},
    {"Brand": "Brands For Less", "Category": "Home & Lifestyle", "Floor": "Lower Ground Floor"},
    {"Brand": "Buccellati", "Category": "Home & Lifestyle", "Floor": "Ground Floor"},
    {"Brand": "Christofle", "Category": "Home & Lifestyle", "Floor": "First Floor"},
    {"Brand": "Crate & Barrel", "Category": "Home & Lifestyle", "Floor": "First Floor"},
    {"Brand": "Crystalline", "Category": "Home & Lifestyle", "Floor": "Lower Ground Floor"},
    {"Brand": "Duxiana", "Category": "Home & Lifestyle", "Floor": "First Floor"},
    {"Brand": "Eden Gallery", "Category": "Home & Lifestyle", "Floor": "First Floor"},
    {"Brand": "Frato", "Category": "Home & Lifestyle", "Floor": "First Floor"},
    {"Brand": "Galeries Lafayette", "Category": "Home & Lifestyle", "Floor": "Ground Floor"},
    {"Brand": "Jashanmal Home Department Store", "Category": "Home & Lifestyle", "Floor": "First Floor"},
    {"Brand": "KARTELL", "Category": "Home & Lifestyle", "Floor": "Lower Ground Floor"},
    {"Brand": "Lakeland", "Category": "Home & Lifestyle", "Floor": "First Floor"},
    {"Brand": "Light of Sakina", "Category": "Home & Lifestyle", "Floor": "First Floor"},
    {"Brand": "MARINA HOME", "Category": "Home & Lifestyle", "Floor": "Lower Ground Floor"},
    {"Brand": "MARKS & SPENCER", "Category": "Home & Lifestyle", "Floor": "First Floor"},
    {"Brand": "Merinos Carpets", "Category": "Home & Lifestyle", "Floor": "First Floor"},
    {"Brand": "Pylones", "Category": "Home & Lifestyle", "Floor": "Second Floor"},
    {"Brand": "Roomours", "Category": "Home & Lifestyle", "Floor": "First Floor"},
    {"Brand": "Serta", "Category": "Home & Lifestyle", "Floor": "First Floor"},
    {"Brand": "TAVOLA", "Category": "Home & Lifestyle", "Floor": "Lower Ground Floor"},
    {"Brand": "Tahran Persian Carpet & Antiques", "Category": "Home & Lifestyle", "Floor": "Second Floor"},
    {"Brand": "The Mattress Store", "Category": "Home & Lifestyle", "Floor": "First Floor"},
    {"Brand": "Versace Home", "Category": "Home & Lifestyle", "Floor": "Lower Ground Floor"},
    {"Brand": "Villeroy & Boch", "Category": "Home & Lifestyle", "Floor": "First Floor"},
    {"Brand": "Yves Delorme", "Category": "Home & Lifestyle", "Floor": "First Floor"},
    {"Brand": "Zara Home", "Category": "Home & Lifestyle", "Floor": "Ground Floor"},

    # Toys & Entertainment
    {"Brand": "Be@rbrick", "Category": "Toys & Entertainment", "Floor": "Ground Floor"},
    {"Brand": "Disney Store", "Category": "Toys & Entertainment", "Floor": "Second Floor"},
    {"Brand": "Early Learning Centre", "Category": "Toys & Entertainment", "Floor": "Second Floor"},
    {"Brand": "Hamleys", "Category": "Toys & Entertainment", "Floor": "Second Floor"},
    {"Brand": "LEGO", "Category": "Toys & Entertainment", "Floor": "Lower Ground Floor"},
    {"Brand": "Party Zone", "Category": "Toys & Entertainment", "Floor": "Second Floor"},
    {"Brand": "TOYS R US", "Category": "Toys & Entertainment", "Floor": "Second Floor"},
    {"Brand": "The Aquarium Store", "Category": "Toys & Entertainment", "Floor": "Second Floor"},
    {"Brand": "The Little Things", "Category": "Toys & Entertainment", "Floor": "Second Floor"},
    {"Brand": "Toy Corner", "Category": "Toys & Entertainment", "Floor": "Second Floor"},
    {"Brand": "ZGAMES", "Category": "Toys & Entertainment", "Floor": "Second Floor"},

    # Food & Beverage
    {"Brand": "% Arabica", "Category": "Food & Beverage", "Floor": "Ground Floor"},
    {"Brand": "% Arabica", "Category": "Food & Beverage", "Floor": "First Floor"},
    {"Brand": "AMAYA", "Category": "Food & Beverage", "Floor": "First Floor"},
    {"Brand": "Black Tap", "Category": "Food & Beverage", "Floor": "Lower Ground Floor"},
    {"Brand": "Charley's Philly Steaks", "Category": "Food & Beverage", "Floor": "Lower Ground Floor"},
    {"Brand": "Grill Shack", "Category": "Food & Beverage", "Floor": "Second Floor"},
    {"Brand": "Kelly's Cajun Grill", "Category": "Food & Beverage", "Floor": "Lower Ground Floor"},
    {"Brand": "Krispy Kreme Doughnuts and Coffee", "Category": "Food & Beverage", "Floor": "Second Floor"},
    {"Brand": "Papa John's", "Category": "Food & Beverage", "Floor": "Second Floor"},
    {"Brand": "Wimpy", "Category": "Food & Beverage", "Floor": "Second Floor"},
    {"Brand": "Bosnian House", "Category": "Food & Beverage", "Floor": "Second Floor"},
    {"Brand": "Burger King", "Category": "Food & Beverage", "Floor": "Second Floor"},
    {"Brand": "Charley's Philly Steaks", "Category": "Food & Beverage", "Floor": "Second Floor"},
    {"Brand": "Circle Of Crust", "Category": "Food & Beverage", "Floor": "Second Floor"},
    {"Brand": "FIVE GUYS", "Category": "Food & Beverage", "Floor": "Lower Ground Floor"},
    {"Brand": "German Doner Kebab", "Category": "Food & Beverage", "Floor": "Second Floor"},
    {"Brand": "Gunaydin", "Category": "Food & Beverage", "Floor": "Second Floor"},
    {"Brand": "HIGH JOINT", "Category": "Food & Beverage", "Floor": "Second Floor"},
    {"Brand": "Hardee's", "Category": "Food & Beverage", "Floor": "Second Floor"},
    {"Brand": "Hatam", "Category": "Food & Beverage", "Floor": "Second Floor"},
    {"Brand": "Iran Zamin", "Category": "Food & Beverage", "Floor": "Lower Ground Floor"},
    {"Brand": "Jollibee", "Category": "Food & Beverage", "Floor": "Second Floor"},
    {"Brand": "KFC", "Category": "Food & Beverage", "Floor": "Second Floor"},
    {"Brand": "KFC", "Category": "Food & Beverage", "Floor": "Lower Ground Floor"},
    {"Brand": "Karam Beirut", "Category": "Food & Beverage", "Floor": "Lower Ground Floor"},
    {"Brand": "McDonald's", "Category": "Food & Beverage", "Floor": "Second Floor"},
    {"Brand": "McDonald's", "Category": "Food & Beverage", "Floor": "Lower Ground Floor"},
    {"Brand": "Noon O Kabab", "Category": "Food & Beverage", "Floor": "Second Floor"},
    {"Brand": "Oakberry", "Category": "Food & Beverage", "Floor": "Second Floor"},
    {"Brand": "Pad Thai", "Category": "Food & Beverage", "Floor": "Second Floor"},
    {"Brand": "Panda Chinese", "Category": "Food & Beverage", "Floor": "Second Floor"},
    {"Brand": "Pizza Hut", "Category": "Food & Beverage", "Floor": "Second Floor"},
    {"Brand": "Pizza Hut", "Category": "Food & Beverage", "Floor": "Lower Ground Floor"},
    {"Brand": "Sah El Nom Express", "Category": "Food & Beverage", "Floor": "Second Floor"},
    {"Brand": "Soy Restaurant", "Category": "Food & Beverage", "Floor": "Second Floor"},
    {"Brand": "Subway", "Category": "Food & Beverage", "Floor": "Second Floor"},
    {"Brand": "Subway - LG Food Court", "Category": "Food & Beverage", "Floor": "Lower Ground Floor"},
    {"Brand": "Texas Chicken", "Category": "Food & Beverage", "Floor": "Second Floor"},
    {"Brand": "Tim Hortons", "Category": "Food & Beverage", "Floor": "Lower Ground Floor"},
    {"Brand": "Umami", "Category": "Food & Beverage", "Floor": "Lower Ground Floor"},
    {"Brand": "Umami", "Category": "Food & Beverage", "Floor": "Second Floor"},
    {"Brand": "Wafi Gourmet", "Category": "Food & Beverage", "Floor": "Lower Ground Floor"},
    {"Brand": "Wendy's", "Category": "Food & Beverage", "Floor": "Second Floor"},
    {"Brand": "Zaatar W Zeit", "Category": "Food & Beverage", "Floor": "Lower Ground Floor"}]

def find_store(storeName):
    for values in dubai_mall:
        print(values["Brand"])



print("========== DUBAI MALL ==========")

user_choice =  input("1. Search Store\n"
      "2. Search Category\n"
      "3. Search Floor\n"
      "4. Add Store\n"
      "5. Remove Store\n"
      "6. Update Store\n"
      "7. Store Statistics\n"
      "8. Floor Statistics\n"
      "9. Category Statistics\n"
      "10. Generate Mall Report\n"
      "11. Exit\n"
        "Please choose your option:")


if user_choice == "1":
    store_name = input("enter store name :").title()
    find_store(store_name)
